# Generated by Django 5.2.7 on 2025-10-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('korean_name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Prix')),
                ('category', models.CharField(choices=[('PLAT', 'Plat'), ('BOISSON', 'Boisson')], default='PLAT', max_length=10, verbose_name='Catégorie')),
                ('is_star', models.BooleanField(default=False, help_text="Cochez pour afficher ce plat sur la page d'accueil.", verbose_name='Plat à la une')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
                'ordering': ['-created_at'],
            },
        ),
    ]
