# Generated by Django 5.2.7 on 2025-10-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('PLAT', 'Plat'), ('SOUPE', 'Soupe')], default='PLAT', max_length=10, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='korean_name',
            field=models.CharField(max_length=200, verbose_name='Nom Coréen'),
        ),
    ]
